# fly.toml app configuration file generated for aoc-slack on 2024-11-29T06:38:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aoc-slack'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
